# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Allen Miyazawa
email: allenmiyazawa@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 Life, tech, and beyond.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: miya526
linkedin_username: allenmiyazawa

# # Build settings
theme: minima
plugins:
  - jekyll-feed

minima:
  skin: dark
  
  social_links:
    - { platform: github,         user_url: "https://github.com/miya526" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/allenmiyazawa/" } 
# Minima social links
# twitter_username: xurxosanz
# github_username: jsanz
# linkedin_username: jsanz
# rss: rss

# # Minima: show excerpts in the frontpage
# show_excerpts: true

# minima:
#   date_format: "%Y-%m-%d"
#   plugins:
#    - jekyll-feed

# # Minima: custom header links
# header_pages:
#   - _pages/frontpage.md
#   - _pages/about.md
#   - _pages/archive.md

# include:
#     - _pages

# exclude: 
#     - .gitignore
#     - docker-compose.yml
#     - Gemfile
#     - Gemfile.lock
#     - LICENSE
#     - README.md